name: GregBrown
favicon: null
layout_spectrum: 0.41099930577911437
typography_spectrum: 0.3318500721361488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.44692372414283454
  lightness: 0.10524316877126694
  saturation: 0.7545282740611583
  rhythmicContrast: 0.9338706554844975
purpose: []
